name: AdvancedKits
main: AdvancedKits\Main
version: 5.1
api: [2.0.0]
author: luca28pet/AndroidHackPro
description: Añade kits a tu servidor
website: crafteolife.nether.co 26417
commands:
 kit:
  description: Obtén un Kit!
  usage: "/kit <nombre del kit>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
 akreload:
  descrpition: Recarga las configuraciones del Kit
  usage: "/akreload"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: "Permite a los usuarios correr el comando /kit"
  default: true
 advancedkits.admin:
  description: "Permite gestionar las características del administrador"
  default: op
