---
# Los usuarios pueden obtener sólo un Kit por vida
one-kit-per-life: true

# Los usuarios podrán recuperar su Kit luego de salir del juego, si no mueren (solo funciona si ésta opción esta en TRUE one-kit-per-life: true)
reset-on-logout: true

# Usar los sistemas de permisos built, aún si usa PurePerms
force-builtin-permissions: true

# Texto del cartel (Puedes cambiarlo por el que quieras, las mayúsculas no importan)
sign-text: "[CrafteoLife]"
...
